### PR TITLE
Added "how to sendmail on windows" step to Czechitas install guide

### PR DESCRIPTION
**Pull request by tomasfejfar**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready to merge?

**Comment by tomasfejfar** [comment]
Jo. Mám to u PR vždycky psát, že je RTM? Beru to tak, že `(!WIP) === RTM` :)

**Comment by TomasVotruba** [comment]
WTF? Please do not use shortcuts and be more explicit. I don't understand empty messages.

Also, stick to one language, English as in commits preferably.

Czechitas page is for your needs, to feel free to tune it/merge it as you need.
.

**Comment by tomasfejfar** [comment]
Fine, sorry :) 

RTM = Ready To Merge
PR = Pull Request
WIP = Work In Progress

**Comment by TomasVotruba** [comment]
:+1:

Thank you

**Pull request merged**
