### PR TITLE
Server ready message

### PR DESCRIPTION
**Pull request by jakubkratina**
I'm not good enough with gulp, so maybe there should be message only if a server successfully started?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for PR! Good to inform user about important stuff.

Does `localhost:8000` work for you? I use is everywhere in manuals.

**Comment by Majkl578** [comment]
I'd prefer 127.91.245.189 rather than 127.0.0.1, since it's already incorrectly bound to 0.0.0.0.

**Comment by jakubkratina** [comment]
Is there a possibility to get an IP from some service?

**Comment by TomasVotruba** [comment]
I'm lost, sorry

**Comment by jakubkratina** [comment]
I don't know either. I always use wrappers. So what do you recommend? What about sending this PR to the #frontend slack channel?

**Comment by TomasVotruba** [comment]
Could you check it `localhost:8000` works?

**Comment by jakubkratina** [comment]
Yep, it works

**Comment by TomasVotruba** [comment]
Awesome. Yes please.

**Comment by jakubkratina** [comment]
Changed.

**Comment by TomasVotruba** [comment]
Thank you! UX lvl up :+1:

**Pull request merged**
