### PR TITLE
Page for press with logos

### PR DESCRIPTION
**Pull request by tomasfejfar**
- [x] Add page
- [x] Add archive with files
- [x] Add to menu

### CODE REVIEW

**Comment by tomasfejfar** [comment]
Any idea why it does not work? It's the same as other pages. 
```
$ vendor\bin\statie generate --server
Value "lang" was not found for "Symplify\Statie\Renderable\File\PostFile" object. Available values are "relativeUrl", "layout", "title", "perex", "author"
```

**Comment by tomasfejfar** [comment]
I'm not sure where to put the link and how to name it. **Press** is fine, although it's not only for press. Also using top menu seems too prominent. What do you think?

**Comment by TomasVotruba** [comment]
@tomasfejfar I will check the lang locally, not sure where it comes from.

Ad menu: what about putting it to footer? I would look for such a thing there.
It's not so relevant for page's target group.

**Comment by tomasfejfar** [comment]
@TomasVotruba I updated the commit to add link to footer instead of header. But I'm still unable to run statie with the same error as above, so I can't check it :/ 

@chemix feel free to update the ZIP with new logo - the branch should be open for commits from maintainers.

**Comment by chemix** [comment]
@tomasfejfar i sended new logo pack to slack

**Comment by TomasVotruba** [comment]
I will manage this.

Thanks for PR @tomasfejfar !

And for new logos @chemix

**Pull request merged**
