### PR TITLE
Content Redesign

### LINKED ISSUE #264: [homepage] add video section
- live streams
- talks records
- meetup live streams on FB Live
- twitch

### PR DESCRIPTION
**Pull request by TomasVotruba**
<strike>#264</strike> not yet

### Related Changes

- add footer
- add Travis Stages
- [x] add link to newsletter to footer: http://us8.campaign-archive.com/home/?u=dcf4beafc191796bf6c47321f&id=c4f7564a7b

### Inspiration

- http://frontendisti.cz
- https://github.com/Frontendisti-cz/frontendisti.cz

### CODE REVIEW

**Comment by TomasVotruba** [comment]
### Before

image

### After

image

**Comment by TomasVotruba** [comment]
Inspiration from: http://frontendisti.cz/

**Comment by TomasVotruba** [comment]
### Before

image


### After

image

**Comment by TomasVotruba** [comment]
To-do :  footer add link to conference, add groups

**Comment by jakubkratina** [comment]
Love the social icons! Good job. Change the photo pls to my current bird photo: https://www.facebook.com/jkratina. Thank ya!

**Comment by TomasVotruba** [comment]
@jakubkratina Máš ho tam fešáku!

**Comment by TomasVotruba** [comment]
Btw, have you somebody implemented a video list from Facebook? 
It looks like we'll have to use FB api, but I'd like to avoid it and use rss/xml. Yet could not find any working, all was turned down.

**Comment by jakubkratina** [comment]
@TomasVotruba why you don't want to use FB API? A proč se vlastně bavíme anglicky? :D

**Comment by TomasVotruba** [comment]
Because GitHub. API is more work than xml parsing.
Got any example code?

**Comment by jakubkratina** [comment]
Unfortunately nope :/

**Comment by TomasVotruba** [comment]
Footer inspiration

image

**Comment by TomasVotruba** [comment]
### Older

footer-old

### Dark

footer-dark

**Comment by TomasVotruba** [comment]
Mergin to finalize huge amount of changes

**Pull request merged**
