### PR TITLE
Fixed responsive display of mentors table

### PR DESCRIPTION
**Pull request by Lexinek**
There was incorrect usage of `table-responsive` css class.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for PR. Could you just send PR before/after so it's easier to see the issue?

**Comment by Lexinek** [comment]
Sure thing! Or you could just trust me ;).
[Before](https://www.dropbox.com/s/p1689ly34eneo86/IMG_1074.PNG?dl=0) and [after](https://www.dropbox.com/s/vpdocf0svogoegx/IMG_1075.PNG?dl=0)

**Comment by TomasVotruba** [comment]
Ou, that is actually bug caused by typo of mine :D 

- https://github.com/pehapkari/pehapkari.cz/commit/02ca8c0461f92b145b4e739bce4ea3a465821deb
- https://github.com/pehapkari/pehapkari.cz/commit/8ec8dedc83a18627c25f2e1af414ee38cb05b9c7

**Comment by TomasVotruba** [comment]
Thanks for screens. Btw, you can upload them directly - like a boss!


## Before 

before

## After

after

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
