### PR TITLE
Article: SOLID principy – 4. díl: Princip odděleného rozhraní

### PR DESCRIPTION
**Pull request by MichalKatuscak**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey @MichalKatuscak 

Thanks for so fast response :+1:

**Comment by TomasVotruba** [comment]
It looks like there is video for 3rd part and post for 4th part: could you check?

https://pehapkari.cz/blog/2017/12/08/solid-principy-4-dil-princip-oddeleneho-rozhrani/

**Comment by MichalKatuscak** [comment]
I'm sorry. Problem is image, not video. I was create fixing pullrequest #359 https://github.com/pehapkari/pehapkari.cz/pull/359

**Comment by TomasVotruba** [comment]
Awesome, thanks!

**Comment by TomasVotruba** [comment]
Btw, feel free to send part 3, 2 and 1 as well. English is great selection of language :ok_hand: 

I can prepare dates to the future, weekly.

**Comment by MichalKatuscak** [comment]
Super :) But will not it be a problem that it is not going from the 1st part and articles are not written in English?

**Comment by TomasVotruba** [comment]
How would you rank it then?

English would be better, as I could spread that to english speaking people on Facebook and not only Czech Republic :)

**Pull request merged**
