### PR TITLE
Fixed docker build + compose + deploy

### PR DESCRIPTION
**Pull request by JanMikes**
@TomasVotruba I renamed gitlab project to https://gitlab.com/open-guys/open-training (originally was open-project), please check settings here on github, section webhooks, but i think it should still work fine :-) just to make sure it did not break things -> if the webhook's url contains id and not name it is okay.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
There is just project id (10224407) and token, nothing related to project name, so I guess it's good to go :)

**Comment by JanMikes** [comment]
@TomasVotruba call for help :-) 

First build failed for Safe\iconv function not found: https://travis-ci.com/TomasVotruba/open-training/builds/99695869#L672

So I removed and now it fails on return type https://travis-ci.com/TomasVotruba/open-training/builds/99699164#L671

Do you have any tip how to fix? add typing that return value `(string)`?

**Comment by TomasVotruba** [comment]
> Do you have any tip how to fix? add typing that return value (string)?

:+1:  Good engouh, this never failed so just to make PHPStan silent

**Comment by TomasVotruba** [comment]
:clap: :cake:

**Pull request merged**
