### PR TITLE
[vocabulary] Added several new terms to vocabulary

### PR DESCRIPTION
**Pull request by klimesf**
Hello, I have added several new terms about testing to vocabulary!

New terms:
- Akceptační test
- Black-box testing
- Code review
- Dynamické testování
- End-to-end test
- Funkcionální test
- Integrační test
- Regresní testování
- Statické testování
- Systémový test
- Test coverage
- TDD
- V-Model
- White-box testing

Enhacements:
- Linked TDD from XP
- Linked design pattern from DAO 

Fixes:
- Fixed typo in VCS (VSC -> VCS)

### CODE REVIEW

**Comment by klimesf** [comment]
I believe this makes me eligible for the awesome Symfony elephant! So I added claim to the rewards.

**Comment by mrtnzlml** [comment]
I fixed just a few typos and merged it into master branch. For the future reference try to squash your commits little bit more. Thanks anyway @klimesf - please contact @TomasVotruba to get your reward...

**Comment by klimesf** [comment]
Thank you :) I will squash them next time.

**Comment by mrtnzlml** [comment]
Just remember - the goal is not to squash all commits into one but squash all related commits into multiple meaningful commits. Look at the link in the previous post as an example. Thanks. :)

**Comment by klimesf** [comment]
Yeah, that's exactly why I didn't do it in the first place. I didn't realize I could squash only some of the commits.

**Pull request closed without merging**
