### PR TITLE
Making open-training as root project

### PR DESCRIPTION
**Pull request by TomasVotruba**
The monorepo is not needed anymore, as only this project will remain

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@JanMikes Now the Docker needs an update to shfit from `projetc/open-training` to `/`.
I tried to move some paths, but I might have missed some :)

**Comment by JanMikes** [comment]
Sure thing, I will have look at it tomorrow 👍

**Comment by JanMikes** [comment]
As well, shall we rename the repo as it is now open-training alone?

**Comment by TomasVotruba** [comment]
> As well, shall we rename the repo as it is now open-training alone?

Done :+1:

**Pull request merged**
