### PR TITLE
[blog] symfonycon-berlin-2016

### PR DESCRIPTION
**Pull request by rozehnal**
Feel free to edit/add more details or whatever...

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Will check tomorrow, thanks a lot! You're faster than my thoughts :D

Let me know if you want to add or improve something @dfridrich @Vrtak-CZ @fprochazka
Multiple PRs are welcomed, if you want to emphasis another talks.

**Comment by TomasVotruba** [comment]
For the start, could you sporten it to 2/3?
Dropping the least interesting talks and event. 

That would make it more readable and focused on content. 

Something like: 5 talks from SymfonyCon 2016 you have to see

**Comment by rozehnal** [comment]
@TomasVotruba - I just removed one article (the shortest one:) ). If you wan't make it more "cool" let me know what would you like to change...factually:)

**Comment by TomasVotruba** [comment]
@rozehnal Thank you. I'll try to be more specific.

So I would suggest:

- Maybe drop "Hackday", since it has no added value for me. 
- Reduce "A mnoho dalšího ..." to just link to source where to find them all.
- Highlight 3 most interesting points in "A year of Symfony". Or was it boring?
- Reduce  "SensioCloud" and  "Symfony Flex" text to half
  - They are too long compared to other topics.
  - What is more relevant? What is does? 
  - What is does?

Pick what you find useful, drop the rest.

**Comment by Vrtak-CZ** [comment]
What about `read-only filesystems` from first @fabpot keynote? I think it's killer feature in Symfony 3.2. Note: Symfony 3.2+ works on read-only filesystems (Google AppEngine, Docker read-only containers etc...).

**Comment by Vrtak-CZ** [comment]
Offtopic: btw why issues / PR etc comments are in English for czech project with czech texts?

**Comment by rozehnal** [comment]
@Vrtak-CZ it should mentioned in first article - second half.

**Comment by Vrtak-CZ** [comment]
@rozehnal i'm so sorry - i need more sleep :-)

**Comment by rozehnal** [comment]
@TomasVotruba @Vrtak-CZ  thanks for the comments. I would not like to shrink the first two paragraphs because they were the most interesting (from my point of view). 

I removed Hackday and shrank a little other parts (really a little so Tomas will not be happy, sorry).

**Comment by TomasVotruba** [comment]
@rozehnal I'm happy with every single step :) Thank your for your cooperation. I will add a bit copy and merge this.

@Vrtak-CZ One of the best reasons for me would be that it's easier to understand for English-only speaking people, who can also add comment/article in here.

**Comment by rozehnal** [comment]
@TomasVotruba modify it as much as you think is reasonable - you are the business guy here:) Thanks!

**Comment by TomasVotruba** [comment]
@rozehnal Ok. I've added my 2 cents :)

**Please check and confirm it's ok**. We can release right it afterwords.

https://github.com/pehapkari/pehapkari.cz/blob/1d5a59f454fbb92b2d324786ce6affbda09ce87c/source/_posts/2016/2016-12-09-jaky-byl-symfonycon-berlin-2016.md

**Comment by TomasVotruba** [comment]
@rozehnal Ready?

**Comment by rozehnal** [comment]
Yep, ready. I just got some mess in git (should be just 8 commits here).

**Comment by TomasVotruba** [comment]
Succeeded by #126

**Comment by TomasVotruba** [comment]
@rozehnal Thanks!

**Pull request closed without merging**
