### PR TITLE
typo

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks. You can merge these right away yourself. No need to check them

**Comment by enumag** [comment]
I know. GH didn't allow me to merge it right away because tests were running. I forgot to check it later.

**Comment by TomasVotruba** [comment]
Oh, I see. Maybe you could add "[skip ci]" to commit message to prevent that.

**Comment by enumag** [comment]
I would have to remember it when commiting here on GH. It is not possible to change to message later without cloning the repo locally.

**Comment by TomasVotruba** [comment]
Sure, I meant that for the future commits :)

**Pull request merged**
