### PR TITLE
Improve installation script

### PR DESCRIPTION
**Pull request by lchrusciel**
Just a proposal of small improvement. I have moved a `cd` command before `composer` one and also added a `gulp` script, so now it can be run locally with `npm run gulp` command. The benefit is that we do not need a global instance of `gulp` in this solution.

Hope you don't mind.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey, thanks for the PR. I understand what it does. Why do you need such feature?

Could you make the command to run website one word? It's very frequently used command (the only one), so be sure to provide nice and easy developer experience.

And also standard.

**Comment by lchrusciel** [comment]
I just don't have a globally installed gulp, as I do not need it frequently. And also, I prefer to have such a libraries run locally, to be sure, that its version is proper. Nothing special ;)
I don't have any good idea how to make it one word... `npm run` is just its own construct, I would need to add some custom, pretty easy script, like `bin/gulp` or something. Not sure if needed.
However, current README instruction will not work, unfortunately :( I will have to at least install `npm intall gulp -g` or something like that to make it work. Also, the line with `cd` should be moved above. 

Should I split the PR to fix a README with the current requirements or just open an issue?

**Comment by TomasVotruba** [comment]
> However, current README instruction will not work, unfortunately :( I will have to at least install npm intall gulp -g or something like that to make it work. Also, the line with cd should be moved above.
>
> Should I split the PR to fix a README with the current requirement steps

That would be great :+1:

**Comment by TomasVotruba** [comment]
Awesome, thank you :+1:

**Pull request merged**
