### PR TITLE
Added brief description of unit test.

### PR DESCRIPTION
**Pull request by racinmat**
Added brief description of unit test.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@mrtnzlml Could you please manage this PR Martin? Thank you

**Comment by mrtnzlml** [comment]
Yes, of course. I am sorry I am not watching this repository - to much spam... :yum:

**Comment by TomasVotruba** [comment]
@mrtnzlml That's completely understandable. If it's okay for you my pinging :)

**Comment by mrtnzlml** [comment]
Merged: https://github.com/pehapkari/pehapkari.cz/commit/afcda343d567bc66bad450bc9327528b16a4c4df

**Comment by TomasVotruba** [comment]
Thank you!

Will do

**Pull request closed without merging**
