### PR TITLE
Removed duplicate code

### PR DESCRIPTION
**Pull request by ivanvgladkov**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey Ivan,

why do you think this is duplicated code?

**Comment by ivanvgladkov** [comment]
Hi Tomas,
because function `findKey` has the same loop, condition and exception throwing, so it would be easier to maintain it in a single place

**Comment by TomasVotruba** [comment]
It seems they have different return values

**Comment by TomasVotruba** [comment]
Ping

**Comment by TomasVotruba** [comment]
Closing as invalid. One return value is key, second is item

**Pull request closed without merging**
