### PR TITLE
Improve english in DDD services article

### PR DESCRIPTION
**Pull request by simara-svatopluk**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Very great :+1: 

Btw, what do you use?

I use this one https://github.com/vlajos/misspell-fixer
Fast and sexy :)

**Comment by simara-svatopluk** [comment]
I use https://grammarly.com and my friends :-P

**Comment by TomasVotruba** [comment]
Cool, where is it in? I use Phpstorm for writing

**Comment by simara-svatopluk** [comment]
I don't use any kind of integration. When I'm done, I copy the article from phpstorm to app.grammarly.com, fix issues and copy it back.

**Pull request merged**
