### PR TITLE
Spelling fix

### PR DESCRIPTION
**Pull request by leninzprahy**
snadně => snadno

### CODE REVIEW

**Comment by leninzprahy** [comment]
I see, that _snadně_ is there more than once...

**Comment by TomasVotruba** [comment]
Thanks for the PR! Feel free to fix the other one too. And the file name.

I'm not sure, it is wrong. I think it depends on the author. 

> ...ale proto ještě nelze první tvar nazývati nesprávným.

Source: http://nase-rec.ujc.cas.cz/archiv.php?art=752 

What do you prefer? @TomasPilar

**Comment by TomasPilar** [comment]
@leninzprahy Thanks for fix it, _snadno_ sounds great.

**Comment by TomasVotruba** [comment]
Fixed and merging

**Pull request merged**
