### PR TITLE
Move DDD implementation article to January

### PR DESCRIPTION
**Pull request by simara-svatopluk**
@TomasVotruba 
Sorry, I misread Your last comment to this article. I fought it is January.
I would like to have the article out now because...
* I'm impatient
* if there are any questions I want to answer them as soon as possible
* I have one more article finished and 2 more in progress... I don't want to bother with them in March ;-)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
No problem. Could you switch dates with one in the queue?

**Comment by simara-svatopluk** [comment]
Ou... why? It would influence someone else's work who maybe plans to deploy one article every week

**Comment by simara-svatopluk** [comment]
Right now I have ready next DDD article. I would like to plan it one week after this one.
I understand that it would be nice to have blog content 2 months to the future, but it is not the way I would prefer to publish articles. I also think article series are independent :-)

**Comment by TomasVotruba** [comment]
The thing is the reader. More people would read all posts if 5 per week, than 5 in one day.
It's common release plan among bloggers I want to respect here.

**Comment by simara-svatopluk** [comment]
Ok, and what is better? One in a day, one in 3 days, one in 6 days, one in a week, one in 8 days, one in 14 days? How did you choose exactly 7 days? and why?

I was waiting for the feedback before issuing next article, until now. If there was a misunderstanding, I could fix it before publishing next one. Now I cannot, I have to publish articles fast just to be sure no one takes my position.

Right now I have time and passion to write articles. I have two finished, one almost and one that I'm working on. This means that the last article will be out on March 14. It is probable that in March, I'll not have enough time to answer discussions and I'll not be interested in fixing two months old articles.

**Comment by simara-svatopluk** [comment]
> More people would read all posts if 5 per week, than 5 in one day.

I agree that two posts in one day may be too much. But it is absolutely ok for me to read one article per day. It also fits with my habits - I read during the morning.

**Comment by simara-svatopluk** [comment]
And let's think about readers. I have some good reactions and articles also probably help, at least to one guy. Now we have more helping information that may save their time and what do we say? Wait a month, now we have articles about another theme.

Could You please answer all arguments?

**Comment by simara-svatopluk** [comment]
@TomasVotruba  No answer for me? :-(

**Comment by TomasVotruba** [comment]
I don't know what to add and don't have time for this at the moment - projects, works, life. In a week it should be better.

**Comment by TomasVotruba** [comment]
Closing as breaking the queue

**Pull request closed without merging**
