### PR TITLE
Develop in Docker container.

### PR DESCRIPTION
**Pull request by newPOPE**
For people who haven't got local environment.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This app only requires PHP 7. I'm afraid adding a Docker container would cause great confusion and implied this app is very complicated.

What issue does this solve?

**Comment by newPOPE** [comment]
Agreed. Solved issue is some of us doesn't have installed PHP and use it in container.

Main object of PR is not replace dev environment but offer an alternative to develop in container. 

And what about confusion, I don't think so. It is really easy example to study.

**Comment by f3l1x** [comment]
I like it. :+1:

**Comment by TomasVotruba** [comment]
@newPOPE Are you actually missing PHP and contributing? 

That would be a valid issue to me. If missing PHP is often blocker to contribute to this page.

**Comment by newPOPE** [comment]
@TomasVotruba sure, reason is I want to contribute but to different projects (PHP, 5.x, 7, ...) so I must install all of these versions? No, just use a container which is builded right for the project.

If you do not this in repository I accept it.

**Comment by TomasVotruba** [comment]
@newPOPE Oh, I understand this better. That's valid use case.

Could you please:

- [] mention this reason in README.md
- [] move the Docker info to `/docs/docker.md` file 
- [] and link to it in README?

That should do it.

**Comment by f3l1x** [comment]
@TomasVotruba Pretty same. I don't have any PHP installed on my computer, only live on container platform. :whale:

**Comment by newPOPE** [comment]
@TomasVotruba nice, I will do it.

**Comment by newPOPE** [comment]
@TomasVotruba updated.

**Comment by TomasVotruba** [comment]
Thanks for patience and your work!

Let's merge this :)

**Pull request merged**
