### PR TITLE
[OpenTraining] Add Invoicing

### LINKED ISSUE #35: Update env
https://symfony.com/blog/improvements-to-the-handling-of-env-files-for-all-symfony-versions

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #35

### CODE REVIEW

**Comment by JanMikes** [comment]
@TomasVotruba let me please know once you are planning to merge this, i will need to update docker build because of the .env file will be versioned and it might cause troubles on production (APP_ENV=dev). 

Or i will just watch this MR and wait until it gets merged 😄

**Comment by TomasVotruba** [comment]
I'll ping you :+1:

**Comment by JanMikes** [comment]
I just realized that this fix might be much easier than I would think. If we add `.env` file into `.dockerignore`, it will be missing completely for production, which is fine and `APP_ENV=dev` for local development in `.env` file is fine as well, so imho that will solve everything.

Other solution will be creating `.env.ci` or `.env.local` for CI/production, but I think solution number 1 is much better and elegant and without need of engineering anything 😉

**Comment by TomasVotruba** [comment]
Merging

**Pull request merged**
