### PR TITLE
Change authors from number-based to name-based

### PR DESCRIPTION
**Pull request by Majkl578**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I would go for 'some_key' to not to create more rules for naming things.

Also, I would also consider using static database. What do you think about this?

**Comment by TomasVotruba** [comment]
We could move to relation database in time, so I would avoid this.

**Comment by TomasVotruba** [comment]
Closing for now.

**Comment by Majkl578** [comment]
Why?

**Comment by TomasVotruba** [comment]
https://github.com/pehapkari/pehapkari.cz/pull/220#issuecomment-281033261

**Comment by Majkl578** [comment]
That isnot really a reason at the moment, unless you plan to implement it anytime soon.

**Comment by TomasVotruba** [comment]
It is. Also got no feedback.

**Pull request closed without merging**
