### PR TITLE
Add Twitch.tv link [WIP]

### PR DESCRIPTION
**Pull request by jakubkratina**
ping @TomasVotruba

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I got all notifications, no need to ping :) 

Btw, could you add some motivation to CTA like: "vysíláme každé 2. úterý"?

**Comment by jakubkratina** [comment]
Where should the like goes?

**Comment by TomasVotruba** [comment]
@jakubkratina FB page events would be the best - https://www.facebook.com/pehapkari/events

**Comment by jakubkratina** [comment]
@TomasVotruba I added the CTA, because you are going to design it, I kept it as is was.

**Comment by TomasVotruba** [comment]
Thank you, merging

**Pull request merged**
