### PR TITLE
Book sharing v.2

### PR DESCRIPTION
**Pull request by tomaskazatel**
Edit book sharing:
1. add neon list for book
2. change list view to table

Ping @TomasVotruba

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you!

**Comment by TomasVotruba** [comment]
I've tuned it a bit in here:

- https://github.com/pehapkari/pehapkari.cz/commit/bb5d6f5a10460a866b1c2c74d522c9fe43a93a13
- https://github.com/pehapkari/pehapkari.cz/commit/7c75e3722c7c05d375680bf67d2f095afa1377c5

**Comment by tomaskazatel** [comment]
I think it's okey. 
Other eyes, better view 👓

**Comment by TomasVotruba** [comment]
True true. I usually need like 4 to 6 more eyes :D

**Pull request merged**
