### PR TITLE
PHP Friends v.2

### PR DESCRIPTION
**Pull request by tomaskazatel**
Make some changes for this issue #66 
- Split one page to two pages.
- Add some inputs.
- Fix bugs on mobile

#90 Edit with comments from this pull request

Is it okay @TomasVotruba and @chemix ?

### CODE REVIEW

**Comment by f3l1x** [comment]
Can you please squash it to single commit? :-)

**Comment by TomasVotruba** [comment]
@f3l1x Can be done merge button now.

@chemix Could you look at this and take care of it please? I don't know what is your idea of this.

@tomaskazatel Is this working on http://pehapkari.cz/kde-najdes-php-kamose/ ? I've tried to add myself but I can't see anything.

**Comment by tomaskazatel** [comment]
@TomasVotruba at this url is old version, you must pull from this this push. This is v.2

**Comment by TomasVotruba** [comment]
@tomaskazatel For further stuffs, deal with @chemix 
I'm taking care of other issues. Just write me PM when this is finished and ready to publish online.

**Comment by tomaskazatel** [comment]
I think this is too old to merge to master. Can we close this pull and i will create new pull with working code for actual version of Pehapkari.cz.

What do you mean @TomasVotruba

**Comment by TomasVotruba** [comment]
Sure, feel free to reopen new one. I will look on it.

**Comment by TomasVotruba** [comment]
It doesn't work and is dead page. It might bring confusion what is wrong. So reverting content for now. 

Feel free to complete anytime later.

**Pull request closed without merging**
