### PR TITLE
Mentors: Sort alphabetically so it's not biased

### PR DESCRIPTION
**Pull request by Majkl578**
Currently the list is biased towards those who came first. Let's be objective.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I had that in mind for months. Your solution is very elegant :+1: 

Could I ask you to add a comment short comment (like name of this PR), so code is readable to others?

**Comment by Majkl578** [comment]
Done.

**Comment by TomasVotruba** [comment]
Thanks a lot!

**Comment by f3l1x** [comment]
Ou nooo. @Majkl578 I've lost my advantage. :-D

**Comment by Majkl578** [comment]
@f3l1x Exactly! :trollface:

**Pull request merged**
