### PR TITLE
Improve columns, upgrade to PHP 7.4

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@JanMikes Could you look at failing Docker image build? I've changed the PHP version and it stopped working.

What else I need to change? I'll try to fix it

**Comment by JanMikes** [comment]
I believe it is because the composer.lock file is locked with 7.3, i will debug locally and let you know asap.

**Comment by JanMikes** [comment]
Ok i found the reason:
```
❯ docker run -it pehapkari/pehapkari.cz-base bash
root@2ff7a11f0c83:/var/www/pehapkari.cz# php -v
PHP 7.3.15 (cli) (built: Feb 26 2020 12:39:53) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
root@2ff7a11f0c83:/var/www/pehapkari.cz#
```

In dockerfile we have base image: 
```
FROM pehapkari/pehapkari.cz-base as production
```

Probably it is not built automatically and pushed to dockerhub

**Comment by JanMikes** [comment]
Ok, problem solved :-) it is automated, but only for master pushes to prevent frauds:

https://github.com/pehapkari/pehapkari.cz/blob/master/.github/workflows/build_base_image.yaml#L6

**Comment by JanMikes** [comment]
You have 2 options now, you can build it locally and push in same way github actions does:

```
docker build . --file .docker/php/Dockerfile --tag pehapkari/pehapkari.cz-base:latest \
                    --cache-from pehapkari/pehapkari.cz-base:latest

docker push pehapkari/pehapkari.cz-base:latest
```

Or 

1st merge base image update and then trigger this pipeline again.

I am sorry for the inconveniences, i did not expect scenario like this to happen.

**Comment by TomasVotruba** [comment]
> 1st merge base image update and then trigger this pipeline again.

Ah, I see. So the image for testing is build from the `master` always.

I'll try that.

**Pull request merged**
