### PR TITLE
Finding PHP friends page

### PR DESCRIPTION
**Pull request by tomaskazatel**
I create firebase with my login. When someone wants credentials let me know.
I don't know how hide api key for firebase...really insecure right :(
@chemix myslel jsi celou podstránku nějak takhle?

### CODE REVIEW

**Comment by chemix** [comment]
@tomaskazatel looks fine

- no phone
- add twitter
- add nickname
- add website
- add linkedin
- add github
- hide form to bootstrap popup modal window? 

We are planing same pehapkari website hackathon at friday afternoon.

**Comment by tomaskazatel** [comment]
@chemix I think that [sweetalert2](https://limonte.github.io/sweetalert2/) is more cool and no jquery required. 

Inputs:
- no phone (ok)
- add twitter (ok)
- add nickname (you want chemix there right :))
- add website (ok)
- add linkedin (i think no)
- add github (yep obviously)

Hackaton sound great let me know if i could get involved.

**Comment by chemix** [comment]
sweet is fine, but we use bootrap for now, and I think jQuery and Boostrap is fine combination for fast web prototyping... ;-)

**Comment by tomaskazatel** [comment]
I think it's better to call directly modal library (sweet) than calling jQuery plus jQueryUI just for modal :) Just my opinion 😎

**Comment by chemix** [comment]
it's not jQueryUI ...  I mean http://getbootstrap.com/javascript/#modals

**Comment by TomasVotruba** [comment]
Please no modals, unless it works perfect on all non-desktop devices. It's really pain to use such sites.

**Comment by chemix** [comment]
@TomasVotruba really ? I think it's not primary action and can be "hidden" to modal. And I hope that bootstrap modal for registration is working everywhere ? not?

**Comment by TomasVotruba** [comment]
@tomaskazatel It's usually fine on desktop, but pain to fill everywhere else.
Please test it first and make sure it works. Also I've seen some report about Google disadvantaging sites with broken modals.

I'd be for moving form to new small page:

- so we can link it directly via url when needed
- and it won't spam the final map page.

**Comment by tomaskazatel** [comment]
@TomasVotruba Sorry for that i will test only on desktop and tablet. I will fixed on mobile devices.
1. I don't know if show map on desktop, tablet and on mobile show sorted table. What do you mean?
2. move form with new inputs to subpage sounds great.

**Comment by TomasVotruba** [comment]
1. I think this will bee too much work to maintain. Not sure.
2. Fine.

I just merge this so you/we can check the result online and send PR with fixes.

**Comment by TomasVotruba** [comment]
Don't forget to reference this PR in new one.

**Comment by tomasfejfar** [comment]
Sorted list with distance + city would be just fine everywhere IMO. It's not so hip as map, but much more usable. Full width map (=on smaller screens) breaks scrolling - it zooms instead. It's OK if it's click activated (as on https://www.shopio.cz/) but that requires additional work.

**Pull request merged**
