### PR TITLE
New words to glossary

### PR DESCRIPTION
**Pull request by kbarborak**
Hi guys. I tried to add some new words to glossary. There are 13 words from your wishlist (#98) and one word of my choice.

1. Agile
2. Algorithm
3. GD/Imagick
4. Instance
5. Constructor
6. MVC
7. Namespace (not listed in referenced issue)
8. Variable
9. Refactoring
10. Singleton
11. UI
12. UX
13. Vendor
14. Webhosting

Let me know what you think and how much points I'll get :-).

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey, welcome to the party :) 

Thanks for such a long list.

@mrtnzlml could you please check it merge it? I will add the points then.

**Comment by mrtnzlml** [comment]
Yes, of course. I'll do it tomorrow. Thank you very much @kbarborak. It's nicely written. Stay tuned...

**Comment by mrtnzlml** [comment]
Gracias @kbarborak, merged.

**Comment by TomasVotruba** [comment]
@mrtnzlml Thank you for checking and merging.

@kbarborak You've been awarded 7 points :1st_place_medal: 

Do you want to spend them or do you plan to get some more? :)

**Comment by kbarborak** [comment]
I want to spend them for Symfony elephpant :-). I am going to contact you on Slack next week.

**Comment by TomasVotruba** [comment]
pxmxh1


It's all yours :) https://github.com/pehapkari/pehapkari.cz/commit/568dc9f3aaf9e7380d83b4a95b0ba07ace43c56e

**Comment by TomasVotruba** [comment]
@kbarborak Just checking, did we already solved it? :) Did Elephant came?

**Pull request closed without merging**
