### PR TITLE
Dockerizing open-training project

### PR DESCRIPTION
**Pull request by JanMikes**
🎉 🎉  Finally, after few days spent I am able to git clone + get the project running in 3 easy commands 😉 The monorepo was a tough enemy for docker 😄 

@TomasVotruba any feedback is appreciated!

### CODE REVIEW

**Comment by JanMikes** [comment]
@TomasVotruba would you mind trying running the project in docker locally? Please note that it should be clean git clone, because of your existing .env file can break docker.

There are 3 simple steps:
1) Switch to the directory of your desired project: `cd projects/open-training`
2) Create **docker-compose.yml** file from template: `cp docker-compose.dist.yml docker-compose.yml` (optionally edit it for your needs, though it should not be necessary)
3) Run `docker-compose up`
4) Enjoy :-) project is available on [localhost:8000](http://localhost:8000)

**Comment by TomasVotruba** [comment]
> There are 3 simple steps:

Could you put that into `bin\run.sh`, so I can just run this a get the result?

```
bin\run.sh
```

**Comment by JanMikes** [comment]
Well, yeah. Though it can not be `bin/run.sh` because it is specific for each project, so it will either have to be in `projects/open-training/bin/run.sh` or `bin/run-open-training.sh` what do you prefer? Another option can be `bin/run.sh open-training` 😄

**Comment by TomasVotruba** [comment]
Let it be `projects/open-training/bin/run-from-docker.sh` :+1: 

Check `bin/console` to see how it works for monorepo. It's basicaly symlink

**Pull request merged**
