### PR TITLE
 Display page titles before site title in HTML head 

### PR DESCRIPTION
**Pull request by finwe**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Not sure I understand. Could you explain the problem?

**Comment by finwe** [comment]
Oh, I see now I accidentaly forcepushed with forgotten debugging null in the template variables. Fixed now.

shot_190513_133856

Current (active) vs. updated html <title> element. HTML titles should reflect page content throughout the site.

**Comment by TomasVotruba** [comment]
I see, better now

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
