### PR TITLE
[blog] console bin (rewrite)

### PR DESCRIPTION
**Pull request by fprochazka**
Rewrite of #289. 

Since I've basically rewritten the whole article from scratch, I thought I might as well add my name to it.
Is it OK with you @TomasVotruba? If not, you're free to use whatever part of this article you want to in the original.

This is a first draft, I'm polishing it a bit more right now. Suggestions are welcome.

Todo:

* [x] make sure `exit()` is called correctly
* [x] selling-point: add section about zsh autocompletion
* [x] verify HttpRequest is really needed in cli

### CODE REVIEW

**Comment by fprochazka** [comment]
@TomasVotruba okey, I'll add it then :)

**Comment by f3l1x** [comment]
@fprochazka @TomasVotruba I think it's good. :-) Thanks for mentioned contributte.

**Comment by f3l1x** [comment]
Maybe one more thing. You can mention also `FriendsOfNette`, there's also similar how-to article. 

https://github.com/FriendsOfNette/fish-tips/blob/master/src/console/cli1-symfony-console.md

**Comment by fprochazka** [comment]
> Miss command registration without tags. That was second take away from my post.

I got confused, because you've already written an article about it. I didn't realize it was a different blog :)

**Comment by fprochazka** [comment]
I think I've addressed all the comments now. cc @TomasVotruba @f3l1x

**Comment by TomasVotruba** [comment]
All right! Thanks for changes.

I think it's ready to merge :+1:

**Comment by TomasVotruba** [comment]
Looks like no more changes or notes are coming, so I'm merging.

Feel free to send PR with post hoc changes, if needed.

Thank you all for great work and cooperation. It's very nice to see to cooperation of authors packages, that might seem concurent. Great job :

**Comment by fprochazka** [comment]
Great, thanks!

**Comment by TomasVotruba** [comment]
Published here https://pehapkari.cz/blog/2017/06/02/best-practice-for-symfony-console-in-nette/

**Comment by TomasVotruba** [comment]
@fprochazka You've got some comments there: https://pehapkari.cz/blog/2017/06/02/best-practice-for-symfony-console-in-nette/#disqus_thread

Since it is under Pehapkar Disqus account, comments needs to be checked manually (by me now :)). I think after first reply you'll get some notification.

**Pull request merged**
