### PR TITLE
Vocabulary: add couple of terms

### PR DESCRIPTION
**Pull request by simara-svatopluk**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi @simara-svatopluk , where can I contact you for the prize? :)

**Comment by simara-svatopluk** [comment]
@TomasVotruba my e-mail is svatopluk.simara@gmail.com

**Comment by TomasVotruba** [comment]
@simara-svatopluk Thanks!

**Comment by mrtnzlml** [comment]
Thanks. I didn't add "Microservice vs. monolit" part because in my opinion it's not term for vocabulary. I also delete word "Služba" because it wasn't good enough and may be vague for a lot of readers...

**Comment by simara-svatopluk** [comment]
I'm glad that the rest is ok.
11/13 - 84%? If I was always so successful...

**Comment by mrtnzlml** [comment]
It is success. And it doesn't matter. You are winner anyway... :)

I don't think the comparison should be in the vocabulary. It doesn't seems to be right. It's also very subjective. You can improve the word "Služba". Unfortunately it may be very abstract for a lot of people (especialy for newcomers) so it needs more careful explanation.

I am sorry I cannot say yes blindly to everything.

**Comment by TomasVotruba** [comment]
I'm in favor of adding terms:

- Microservice
- Monolit

@mrtnzlml I would rather give feedback how to improve, then accept/deny. What do you think?

**Comment by mrtnzlml** [comment]
"Monolit" and "Microservice" are already here. I rejected third term "Microservice vs. monolit".

I also rejected "Služba" because from my point of view it wasn't good enough but it doesn't make sense to stop another 10 words because of my opinion. So it's partially accepted with feedback and possibility to improve it. Pushing forward method... :)

If you think it's wrong - I'll stop doing that.

**Comment by simara-svatopluk** [comment]
The work system depends...
If you want to have things done quickly, then you will have to do the corrections.
If you want to teach me, then you'll give me feedback, I will do the corrections and the process will be slower. But next time I won't repeat the same mistake, maybe.

It depends...

**Comment by mrtnzlml** [comment]
You still have opportunity to fix it. It's not yin and yang...

**Comment by simara-svatopluk** [comment]
Sorry, right now I've lost in this conversation.
This pull request is already merged, changes can be done only in a new pull request, right?
This conversation is about what? About improving merging process? About fixing vocabulary term?

**Comment by TomasVotruba** [comment]
@mrtnzlml Oh, I though reason was only comparison. Having these terms there makes it better point for me. Thanks for completing.

I'm fine with you approach then.

Personally I keep PRs open until both sides are clear about each others intentions and reasons. So when it's closed, discussion is closed as well. With peace the better.

**Pull request closed without merging**
