### PR TITLE
Added a RSS feed for the blog

### PR DESCRIPTION
**Pull request by javiereguiluz**
This tries to solve #134 because I want to subscribe to the feed of this blog.

Note: I don't speak Czech and I've never used Latte templates, so I apologize in advance for all the mistakes :)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank for such a fast PR. We should email each other more often ;)
I see you are fast leaner :)

I will check it tonight and merge it if correct.

**Comment by TomasVotruba** [comment]
Merged with few fixes. Thank you!

**Comment by TomasVotruba** [comment]
Could you check final RSS file?

http://pehapkari.cz/rss.xml

**Comment by javiereguiluz** [comment]
@TomasVotruba thanks for fixing this and merging it. Don't worry about the commit authorship ... I've messed things myself lots of times :(

I tested the RSS feed with Firefox, Feedly and a desktop RSS reader ... it seems to be correct. However, the W3C validator shows 2 errors:

* `<language>cz</language>` Error: "language must be an ISO-639 language code".  Meybe it's better to remove this tag because you are blogging in more than 1 language?
* `Missing atom:link with rel="self"`  You need to add the following:

```xml
<channel>
    ...
    <atom:link href="{$siteUrl}/rss.xml" rel="self" type="application/rss+xml" />
    ...
</channel>
```

**Comment by TomasVotruba** [comment]
@javiereguiluz Thanks a lot for checking multiple readers!

Done and done:

- https://github.com/pehapkari/pehapkari.cz/commit/ea33eb08c99a2a1a13ee5f2d82f8250c293acdb8
- https://github.com/pehapkari/pehapkari.cz/commit/14f2e5278481a63e76c60f43cd2e444dafcd541a

**Pull request merged**
