### PR TITLE
Update napis-clanek-vem-si-darek.latte

### PR DESCRIPTION
**Pull request by martinahynkova**

### CODE REVIEW

**Comment by Majkl578** [comment]
Velká písmena u zájmen se používají především ve formální komunikaci. Naopak malá jsou vhodná v případě, kdy k adresátovi (čtenáři) máme bližší vztah.
Vzhledem k tomu, že celý web je psaný neformálně a přátelsky, nemyslím si, že by se měly používat zájmena s velkým písmenem.

Reference:
* http://nase-rec.ujc.cas.cz/archiv.php?art=4554
* http://www.mojecestina.cz/article/2008090301-velka-pismena-vas-nebo-vas

**Comment by TomasVotruba** [comment]
Díky za návrh Marťo. Je to spíš otázka brandu. 

Myslím, že jsem to jel kdysi na začátku, ale pak jsem od toho asi upustil, takže by to teď nebylo konzistentní.

(Nevidím tu nikde info o zavření, tak jsem zkusil otevřít. Nevíte proč?)

**Comment by TomasVotruba** [comment]
@Majkl578 Don't close PR like this, thank you.

**Comment by Majkl578** [comment]
@TomasVotruba Like what? Přečti si nejdřív můj komentář výše (https://github.com/pehapkari/pehapkari.cz/pull/279#issuecomment-301347911), myslím, že jsem důvod zavření celkem jasně sdělil (viz 2. věta).

**Comment by TomasVotruba** [comment]
@Majkl578 Don't close or merge any PR. No matter reason you might have.

**Comment by Majkl578** [comment]
Should I mention you creating random pull requests that you merge in few minutes?

**Comment by fprochazka** [comment]
image

**Comment by TomasVotruba** [comment]
@Majkl578 I'd love to explain you importance of empathy in these situations, as I see it much more important than systematic and (your) logical thinking you approach this with, but I'm not sure how to do so.

I tried that before but only get "do-not-care-you-are-bad" response from you. So I'm demotivated to do it again.

**Comment by fprochazka** [comment]
I think @Majkl578 have reasoned closing of this PR exceptionally nicely. Did @martinahynkova felt offended?

**Comment by TomasVotruba** [comment]
She didn't even knew there might be something like NO because 1 person doesn't agree. That's the problem.

Also, this is rather marketing and brand approach rather than rules of Czech lanaguge. 

I would not close PR at project that other people build without asking them, what they mean by that. I understand it was my mistake to give the member access, which might imply this is the desired. I removed that afterward to prevent such missunderstandings in the future.

I gave member access to other people and we usually discuss or ask one another before closing PRs.

**Comment by fprochazka** [comment]
@TomasVotruba now the intention is much clearer, thanks for explaining. I guess this should have been said while you have assigned the rights :)

I would also assume, that I have the power to close PRs on my own, if I were given the rights to do so. I think of it as helping the main-maintainer, but it really depends on the habits and type of individual projects.

**Comment by TomasVotruba** [comment]
@fprochazka Thank you for feedback. I will do for next time!

I'd love to setup this on system level, so it's not "I have to rememer what can I do" kind of thing.
I didn't find any option to allow merge and prevent closing PR, if you are a team member.
Also there is no option (I'm aware of) to limit level of write access, only for outside collaborators. 

Do you have any experience with this?

**Comment by fprochazka** [comment]
@TomasVotruba not really, I give rights to people I trust to have the best intentions with the project so I don't try to limit them with force.

**Comment by TomasVotruba** [comment]
@fprochazka Much to learn I have.

**Pull request closed without merging**
