### PR TITLE
added few things to vocabulary

### PR DESCRIPTION
**Pull request by foxycode**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Prosím o čeknutí a merge @mrtnzlml 
Děkuju

**Comment by mrtnzlml** [comment]
Protip: try to keep your forks rebased on top of `master` branch when sending PR. It's less confusing and not so error prone. Thanks... :)

Also it's better to use less complex language for vocabulary.

Merged by https://github.com/pehapkari/pehapkari.cz/commit/3165dae05e8d70ce33409145eb62de9dcc5b7b2c

**Comment by foxycode** [comment]
@mrtnzlml I definitely rebased before pull. There must have been updates btween that time.

What exactly seems complex?

**Comment by mrtnzlml** [comment]
Ok, never mind - nothing happened.

Great example with big complexity is word `factory`. I prefer shorter and less vague definitions **for newcomers** (more objective arguments). I merged it with little changes, but don't worry - you'll get your points anyway.

**Pull request closed without merging**
