### PR TITLE
Typos: Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by Majkl578**
This is just a simple sed:
```bash
$ sed -i -E 's/\s+$//g' source/_posts/201*/*
```

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Awesome! Thank you

**Comment by TomasVotruba** [comment]
Do you think it could be added in CI in some way?

**Comment by Majkl578** [comment]
I was considering some way to enforce it on code-style level, but so far I don't know any good tool to enforce style for text files... Or at least tool to enforce .editorconfig settings. Do you know anything?
At least this one could be easily changed to grep + failure on CI when violated.

**Comment by TomasVotruba** [comment]
Could you write the same think in PHP? In two tways - check (do not change, just warn) and fix (change).

I could turn it into Sniff easily.

**Comment by Majkl578** [comment]
Sure, simple: https://3v4l.org/ggKba

**Comment by Majkl578** [comment]
Merging, task for sniff moved to #256.

**Comment by TomasVotruba** [comment]
:+1:  Thank you

**Pull request merged**
