### PR TITLE
[CodingStandard] drop annoying rules

### PR DESCRIPTION
**Pull request by TomasVotruba**
Based on https://github.com/pehapkari/pehapkari.cz/issues/287

I realized, [object-calisthenics](https://github.com/object-calisthenics/phpcs-calisthenics-rules) might be too strict architecture pattern. And I don't want to make contributting to community blog pain, just because of them.

Sorry about that @jkuchar, that was not intention of this.

### CODE REVIEW

**Comment by jkuchar** [comment]
Object-calisthenics seems reasonable for pehapkari code itself. Why are you dropping that completely?

Isn't just better to distinguish between actual code of website and blog posts code?

**Comment by TomasVotruba** [comment]
@jkuchar Well, here is only blost post code. 

You probably talk about Statie - https://github.com/Symplify/Symplify/tree/master/packages/Statie
These rules are kept there.

**Comment by jkuchar** [comment]
Ahh, got it!

**Comment by TomasVotruba** [comment]
Sure :+1:

**Comment by TomasVotruba** [comment]
Meriging!

**Comment by jkuchar** [comment]
Unfortunately it still does not work on Windows.

[output.txt](https://github.com/pehapkari/pehapkari.cz/files/1065764/output.txt)

**Pull request merged**
